import 'picturefill';
import foo from './foo';
import bar from './bar';
import yo from './yo';
import emailSignUp from '../component/emailSignUp';
import emailUnsubscribe from '../component/emailUnsubscribe';
import '../style/index.scss';
import '../image/bar.svg';
import '../image/foo/foo.svg';
foo();
bar();
yo();
emailSignUp();
emailUnsubscribe();
